INSERT INTO movie(title, year, genre, summary, image,quality,"length") VALUES('The Lion King',2019,8,'After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.','https://m.media-amazon.com/images/M/MV5BMjIwMjE1Nzc4NV5BMl5BanBnXkFtZTgwNDg4OTA1NzM@._V1_.jpg','HD',88),
								('Jojo Rabbit',2019,6,'A young German boy in the Hitler Youth whose hero and imaginary friend is the country is dictator is shocked to discover that his mother is hiding a Jewish girl in their home.','https://m.media-amazon.com/images/M/MV5BZjU0Yzk2MzEtMjAzYy00MzY0LTg2YmItM2RkNzdkY2ZhN2JkXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_QL75_UX190_CR0,2,190,281_.jpg','HD',135),
								('Mad Max: Fury Road',2015,4,'The series follows the adventures of Rockatansky, a police officer in a future Australia which is experiencing societal collapse due to war and critical resource shortages.','https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg','4k',120),
								('Joker',2019,7,'"The rise of Arthur Fleck, from aspiring stand-up comedian and pariah to Gotham is clown prince and leader of the revolution.','"https://image.pmgstatic.com/cache/resized/w420/files/images/film/posters/163/823/163823918_6fc912.jpg','HD',122),
								('Ready Player One',2018,4,'When the creator of a virtual reality called the OASIS dies, he makes a posthumous challenge to all OASIS users to find his Easter Egg, which will give the finder his fortune and control of his world.','"https://m.media-amazon.com/images/M/MV5BY2JiYTNmZTctYTQ1OC00YjU4LWEwMjYtZjkwY2Y5MDI0OTU3XkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_.jpg','FHD',140),
								('Dune',2021,4,'A noble family becomes embroiled in a war for control over the galaxy is most valuable asset while its heir becomes troubled by visions of a dark future','"https://www.spietati.it/wp-content/uploads/2021/10/dune_loc1.jpg','4k',155),
								('The Batman',2022,7,'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.','"https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_.jpg','4k',176),
								('Spider-Man: Into the Spider-Verse',2018,8,'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.','"https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_.jpg','FHD',140),
								('Baywatch',2017,6,'Devoted lifeguard Mitch Buchannon butts heads with a brash new recruit, as they uncover a criminal plot that threatens the future of the bay.','"https://image.tmdb.org/t/p/original/omsKDgiLOMoD4APCbIUIcja8NaB.jpg','HD',121),
								('San Andreas',2015,1,'In the aftermath of a massive earthquake in California, a rescuechopper pilot makes a dangerous journey with his ex-wife across the state in order to rescue his daughter.','"https://m.media-amazon.com/images/M/MV5BNzZhYmQ2NGMtZmRmYi00NzgzLTllNmUtNDQwZDAxMmE3NzI0XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg','4k',114),
								('Ted 2',2015,6,'Newlywed couple Ted and Tami-Lynn want to have a baby, but in order to qualify to be a parent, Ted will have to prove he is a person in a court of law.','"https://m.media-amazon.com/images/M/MV5BMjEwMDg3MDk1NF5BMl5BanBnXkFtZTgwNjYyODA1NTE@._V1_.jpg','4k',116),
								('Suicide Squad',2016,1,'A secret government agency recruits some of the most dangerous incarcerated supervillains to form a defensive task force. Their first mission: save the world from the apocalypse.','"https://m.media-amazon.com/images/M/MV5BMjM1OTMxNzUyM15BMl5BanBnXkFtZTgwNjYzMTIzOTE@._V1_.jpg','HD',130),
								('Fast & Furious 7',2015,1,'Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.','"https://static.wikia.nocookie.net/fastandfurious/images/a/aa/FF7_officialposter.jpg/revision/latest?cb=20200323092117','4k',140),
								('No Time to Die',2021,1,'James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.','https://m.media-amazon.com/images/M/MV5BYWQ2NzQ1NjktMzNkNS00MGY1LTgwMmMtYTllYTI5YzNmMmE0XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_.jpg','HD',157),
								('Coco',2017,6,'Aspiring musician Miguel, confronted with his family is ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.','https://www.imdb.com/title/tt2380307/mediaviewer/rm585455872/?ref_=tt_ov_i','4k',163),
								('It',2017,3,'In a small town in Maine, seven children known as The Losers Club come face to face with life problems, bullies and a monster that takes the shape of a clown called Pennywise.','https://image.tmdb.org/t/p/w300/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg','HD',105),
								('Black Panther',2018,1,'T`Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country is past.','https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_.jpg','HD',108),
								('Avengers: Infinity War',2018,1,'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.','https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_.jpg','FHD',149),
								('Jumanji: Welcome to the Jungle',2017,6,'Four teenagers are sucked into a magical video game, and the only way they can escape is to work together to finish the game.','https://m.media-amazon.com/images/M/MV5BODQ0NDhjYWItYTMxZi00NTk2LWIzNDEtOWZiYWYxZjc2MTgxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg','FHD',119),
								('Zootopia',2016,8,'In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy','https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_FMjpg_UX1000_.jpg','HD',108),
								('Get Out',2017,3,'A young African-American visits his White girlfriends parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.','https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_FMjpg_UX1000_.jpg','HD',104),
								('Murder on the Orient Express',2017,5,'When a murder occurs on the train on which he is travelling, celebrated detective Hercule Poirot is recruited to solve the case.','https://m.media-amazon.com/images/M/MV5BMTk5OGFiYzktMTkwNS00ZjQ5LWFkNGQtNGM0MjA4MWE2MDIwXkEyXkFqcGdeQXVyODY1NDk1NjE@._V1_.jpg','HD',114),
								('Blade Runner 2049',2017,4,'Young Blade Runner Ks discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who has been missing for thirty years.','https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_FMjpg_UX1000_.jpg','HD',163);

INSERT INTO genre(title) VALUES('akcion'),('fantasi'),('horror'),('science fiction'),('mystery'),('comedy'),('thriller'),('animated');


